from __future__ import annotations

import pandas as pd
import plotly.express as px
import streamlit as st

from src.dashboard.page_renderers._methodology import section as _method

STATUS_COLORS = {
    "Operating":    "#2563eb",
    "Construction": "#f59e0b",
    "Planned":      "#10b981",
    "Proposed":     "#8b5cf6",
    "Shutdown":     "#ef4444",
}


def _code(snippet: str) -> None:
    with st.expander("Show code"):
        st.code(snippet.strip(), language="python")


def render(
    reactors: pd.DataFrame,
    countries: pd.DataFrame,
    pipeline: pd.DataFrame,
    taxonomy: pd.DataFrame,
) -> None:
    st.subheader("Exploratory Data Analysis — Global Nuclear Fleet")
    st.caption(
        "Each section shows the chart and the exact Python code used to produce it. "
        "Data is loaded from the processed tables generated by `python run_pipeline.py`."
    )

    # ── 1. Global snapshot ────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 1. Global Snapshot")

    op  = reactors[reactors.status_group == "Operating"]
    uc  = reactors[reactors.status_group == "Construction"]
    gen_85 = op.capacity_mwe.sum() / 1000 * 0.85 * 8.76

    c = st.columns(5)
    c[0].metric("Total records",          f"{len(reactors):,}")
    c[1].metric("Countries",              reactors.country.nunique())
    c[2].metric("Operating GWe",          f"{op.capacity_mwe.sum()/1000:,.1f}")
    c[3].metric("Under construction GWe", f"{uc.capacity_mwe.sum()/1000:,.1f}")
    c[4].metric("Est. generation (85% CF)", f"{gen_85:,.0f} TWh/yr")

    _code("""
import pandas as pd
reactors = pd.read_csv("data/processed/reactors_master.csv")

op  = reactors[reactors.status_group == "Operating"]
uc  = reactors[reactors.status_group == "Construction"]

print(f"Total records:        {len(reactors)}")
print(f"Countries:            {reactors.country.nunique()}")
print(f"Operating GWe:        {op.capacity_mwe.sum()/1000:.1f}")
print(f"Under construction:   {uc.capacity_mwe.sum()/1000:.1f} GWe")
print(f"Est. generation 85%:  {op.capacity_mwe.sum()/1000 * 0.85 * 8.76:,.0f} TWh/yr")
""")

    # ── 2. Capacity by country ────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 2. Capacity by Country and Status")

    tab1, tab2 = st.tabs(["Operating — top 15", "All statuses stacked"])

    with tab1:
        cap = (
            op.groupby("country")["capacity_mwe"].sum().div(1000)
            .sort_values(ascending=False).head(15).reset_index()
            .rename(columns={"country":"Country","capacity_mwe":"GWe"})
        )
        fig = px.bar(cap, x="Country", y="GWe", template="plotly_white",
                     color_discrete_sequence=["#2563eb"])
        fig.update_layout(xaxis_title="", margin=dict(t=10))
        st.plotly_chart(fig, use_container_width=True)

    with tab2:
        all_cap = (
            reactors[reactors.status_group.isin(["Operating","Construction","Planned","Proposed"])]
            .groupby(["country","status_group"])["capacity_mwe"].sum().div(1000)
            .reset_index()
            .rename(columns={"country":"Country","status_group":"Status","capacity_mwe":"GWe"})
            .sort_values("GWe", ascending=False)
        )
        fig2 = px.bar(all_cap, x="Country", y="GWe", color="Status",
                      color_discrete_map=STATUS_COLORS,
                      template="plotly_white", barmode="stack")
        fig2.update_layout(xaxis_title="", margin=dict(t=10),
                           xaxis=dict(tickangle=-40), height=420)
        st.plotly_chart(fig2, use_container_width=True)

    _code("""
# Operating capacity — top 15
cap = (
    reactors[reactors.status_group == "Operating"]
    .groupby("country")["capacity_mwe"]
    .sum()
    .div(1000)               # MWe → GWe
    .sort_values(ascending=False)
    .head(15)
    .reset_index()
)
cap.columns = ["Country", "GWe"]

# All statuses stacked
all_cap = (
    reactors[reactors.status_group.isin(["Operating","Construction","Planned","Proposed"])]
    .groupby(["country","status_group"])["capacity_mwe"]
    .sum().div(1000)
    .reset_index()
)
""")

    # ── 3. Technology mix ─────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 3. Technology Mix — Fleet vs Pipeline")

    left, right = st.columns(2)
    with left:
        st.caption("Operating fleet (by capacity, GWe)")
        tech = (
            op.groupby("technology_family")["capacity_mwe"].sum().div(1000)
            .sort_values(ascending=False).reset_index()
            .rename(columns={"technology_family":"Technology","capacity_mwe":"GWe"})
        )
        fig = px.pie(tech, names="Technology", values="GWe",
                     hole=0.35, template="plotly_white")
        fig.update_layout(margin=dict(t=10))
        st.plotly_chart(fig, use_container_width=True)

    with right:
        st.caption("Pipeline — Construction + Planned (GWe)")
        pipe_tech = (
            pipeline[pipeline.status_group.isin(["Construction","Planned"])]
            .groupby("technology_family")["capacity_mwe"].sum().div(1000)
            .sort_values(ascending=False).reset_index()
            .rename(columns={"technology_family":"Technology","capacity_mwe":"GWe"})
        )
        fig2 = px.bar(pipe_tech, x="Technology", y="GWe",
                      template="plotly_white", color_discrete_sequence=["#f59e0b"])
        fig2.update_layout(xaxis_title="", margin=dict(t=10),
                           xaxis=dict(tickangle=-25))
        st.plotly_chart(fig2, use_container_width=True)

    lwr_share = tech.loc[tech.Technology.str.contains("Light Water",na=False), "GWe"].sum() / tech.GWe.sum() * 100
    st.caption(
        f"Light Water Reactors account for **{lwr_share:.0f}%** of operating capacity. "
        "The pipeline shows a higher share of advanced designs (HPR-1000, VVER-1200, SMR) "
        "but deployment history for most remains limited."
    )

    _code("""
pipeline = pd.read_csv("data/processed/reactor_pipeline.csv")

# Fleet technology mix
fleet_tech = (
    reactors[reactors.status_group == "Operating"]
    .groupby("technology_family")["capacity_mwe"]
    .sum().div(1000)
    .sort_values(ascending=False)
)

# Pipeline technology mix (Construction + Planned)
pipe_tech = (
    pipeline[pipeline.status_group.isin(["Construction","Planned"])]
    .groupby("technology_family")["capacity_mwe"]
    .sum().div(1000)
    .sort_values(ascending=False)
)

print("Fleet (GWe):")
print(fleet_tech.round(1))
print("\\nPipeline (GWe):")
print(pipe_tech.round(1))
""")

    # ── 4. Fleet age ──────────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 4. Fleet Age Distribution")

    op_dated = op.dropna(subset=["age_years"])
    median_age = op_dated["age_years"].median()
    pct_over40 = (op_dated["age_years"] >= 40).mean() * 100

    left, right = st.columns(2)
    with left:
        fig = px.histogram(op_dated, x="age_years", nbins=30, template="plotly_white",
                           labels={"age_years":"Age (years)"},
                           color_discrete_sequence=["#2563eb"])
        fig.add_vline(x=median_age, line_dash="dash", line_color="red",
                      annotation_text=f"Median: {median_age:.0f} yr",
                      annotation_position="top right")
        fig.update_layout(margin=dict(t=10))
        st.plotly_chart(fig, use_container_width=True)

    with right:
        age_c = (
            op_dated.groupby("country")["age_years"].mean()
            .sort_values(ascending=False).head(15).reset_index()
            .rename(columns={"country":"Country","age_years":"Avg age (yr)"})
        )
        fig2 = px.bar(age_c, x="Country", y="Avg age (yr)",
                      template="plotly_white",
                      color="Avg age (yr)", color_continuous_scale="Reds")
        fig2.update_layout(margin=dict(t=10), xaxis_title="",
                           xaxis=dict(tickangle=-35), coloraxis_showscale=False)
        st.plotly_chart(fig2, use_container_width=True)

    st.caption(
        f"Median fleet age: **{median_age:.0f} years** · "
        f"**{pct_over40:.0f}%** of operating units are 40+ years old. "
        "Countries with the oldest fleets face capacity replacement pressure — "
        "a structural driver of new-build activity."
    )

    _code("""
op = reactors[reactors.status_group == "Operating"].copy()
op_dated = op.dropna(subset=["age_years"])

median_age  = op_dated["age_years"].median()
pct_over_40 = (op_dated["age_years"] >= 40).mean() * 100

print(f"Median age: {median_age:.0f} years")
print(f"Units aged 40+: {pct_over_40:.0f}%")

# Average age by country
age_by_country = (
    op_dated.groupby("country")["age_years"]
    .mean()
    .sort_values(ascending=False)
    .round(1)
)
print(age_by_country.head(10))
""")

    # ── 5. Historical buildout ─────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 5. Historical Buildout by Decade")

    r_dated = reactors[reactors.commercial_operation_date.notna()].copy()
    r_dated["year"] = pd.to_datetime(r_dated["commercial_operation_date"]).dt.year
    r_dated["decade"] = (r_dated["year"] // 10) * 10

    by_dec = (
        r_dated.groupby(["decade","technology_family"])["capacity_mwe"]
        .sum().div(1000).reset_index()
        .rename(columns={"decade":"Decade","technology_family":"Technology","capacity_mwe":"GWe"})
    )

    fig = px.bar(by_dec, x="Decade", y="GWe", color="Technology",
                 template="plotly_white", barmode="stack",
                 labels={"Decade":"Decade","GWe":"Capacity commissioned (GWe)"})
    fig.update_layout(margin=dict(t=10), xaxis=dict(type="category"))
    st.plotly_chart(fig, use_container_width=True)

    peak_dec = by_dec.groupby("Decade")["GWe"].sum().idxmax()
    peak_gwe = by_dec.groupby("Decade")["GWe"].sum().max()
    st.caption(
        f"Peak decade: **{peak_dec}s** ({peak_gwe:.0f} GWe commissioned). "
        "Sharp slowdown in 1990s–2000s post-Chernobyl. "
        "Recovery in 2010s–20s driven by China, UAE, and first EPR/AP1000 commissioning."
    )

    _code("""
r_dated = reactors[reactors.commercial_operation_date.notna()].copy()
r_dated["year"]   = pd.to_datetime(r_dated["commercial_operation_date"]).dt.year
r_dated["decade"] = (r_dated["year"] // 10) * 10

by_decade = (
    r_dated.groupby(["decade","technology_family"])["capacity_mwe"]
    .sum()
    .div(1000)      # MWe → GWe
    .unstack(fill_value=0)
)

print("GWe commissioned per decade by technology:")
print(by_decade.round(1))

peak = by_decade.sum(axis=1).idxmax()
print(f"\\nPeak decade: {peak}s ({by_decade.sum(axis=1)[peak]:.0f} GWe)")
""")

    # ── 6. Nuclear share ──────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 6. Nuclear Share of Electricity by Country")

    c_share = (
        countries.dropna(subset=["nuclear_share_percent"])
        .query("nuclear_share_percent > 0")
        .sort_values("nuclear_share_percent", ascending=False)
    )

    fig = px.bar(c_share, x="country", y="nuclear_share_percent",
                 color="nuclear_share_percent", color_continuous_scale="Blues",
                 labels={"country":"Country","nuclear_share_percent":"Nuclear share (%)"},
                 template="plotly_white")
    fig.add_hline(y=30, line_dash="dot", line_color="orange",
                  annotation_text="30% threshold", annotation_position="top right")
    fig.update_layout(margin=dict(t=10), xaxis_title="",
                      xaxis=dict(tickangle=-40), coloraxis_showscale=False)
    st.plotly_chart(fig, use_container_width=True)

    above_30 = (c_share.nuclear_share_percent >= 30).sum()
    st.caption(
        f"**{above_30} countries** derive 30%+ of electricity from nuclear. "
        "France leads at ~65%. New entrants (Turkey, Egypt, Bangladesh) are at 0% "
        "but have construction projects underway."
    )

    _code("""
countries = pd.read_csv("data/processed/country_nuclear_profile.csv")

nuclear_share = (
    countries[countries.nuclear_share_percent > 0]
    .sort_values("nuclear_share_percent", ascending=False)
    [["country","nuclear_share_percent","electricity_generation_twh","nuclear_generation_twh"]]
)

print(nuclear_share.head(15).to_string(index=False))

above_30 = (nuclear_share.nuclear_share_percent >= 30).sum()
print(f"\\nCountries with nuclear share ≥ 30%: {above_30}")
""")

    # ── 7. Regional breakdown ─────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 7. Regional Breakdown")

    left, right = st.columns(2)
    with left:
        st.caption("Operating capacity by region (GWe)")
        reg_op = (
            op.groupby("region")["capacity_mwe"].sum().div(1000)
            .sort_values(ascending=False).reset_index()
            .rename(columns={"region":"Region","capacity_mwe":"GWe"})
        )
        fig = px.pie(reg_op, names="Region", values="GWe",
                     hole=0.35, template="plotly_white")
        fig.update_layout(margin=dict(t=10))
        st.plotly_chart(fig, use_container_width=True)

    with right:
        st.caption("Under-construction capacity by region (GWe)")
        reg_uc = (
            uc.groupby("region")["capacity_mwe"].sum().div(1000)
            .sort_values(ascending=False).reset_index()
            .rename(columns={"region":"Region","capacity_mwe":"GWe"})
        )
        fig2 = px.bar(reg_uc, x="Region", y="GWe",
                      template="plotly_white", color_discrete_sequence=["#f59e0b"])
        fig2.update_layout(margin=dict(t=10), xaxis_title="")
        st.plotly_chart(fig2, use_container_width=True)

    _code("""
by_region = reactors.groupby(["region","status_group"])["capacity_mwe"].sum().div(1000).unstack(fill_value=0)
print("Capacity (GWe) by region and status:")
print(by_region.round(1))

# Share of under-construction capacity by region
uc = reactors[reactors.status_group == "Construction"]
uc_region = uc.groupby("region")["capacity_mwe"].sum().div(1000).sort_values(ascending=False)
print("\\nUnder construction by region (GWe):")
print(uc_region.round(1))
""")

    # ── 8. Vendor landscape ───────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 8. Vendor Landscape")

    left, right = st.columns(2)
    with left:
        st.caption("Operating fleet — top vendors by GWe")
        vendor_op = (
            op.groupby("vendor")["capacity_mwe"].sum().div(1000)
            .sort_values(ascending=False).head(12).reset_index()
            .rename(columns={"vendor":"Vendor","capacity_mwe":"GWe"})
        )
        fig = px.bar(vendor_op, x="GWe", y="Vendor", orientation="h",
                     template="plotly_white", color_discrete_sequence=["#2563eb"])
        fig.update_layout(margin=dict(t=10), yaxis=dict(autorange="reversed"))
        st.plotly_chart(fig, use_container_width=True)

    with right:
        st.caption("Under construction — top vendors by GWe")
        vendor_uc = (
            uc.groupby("vendor")["capacity_mwe"].sum().div(1000)
            .sort_values(ascending=False).head(12).reset_index()
            .rename(columns={"vendor":"Vendor","capacity_mwe":"GWe"})
        )
        fig2 = px.bar(vendor_uc, x="GWe", y="Vendor", orientation="h",
                      template="plotly_white", color_discrete_sequence=["#f59e0b"])
        fig2.update_layout(margin=dict(t=10), yaxis=dict(autorange="reversed"))
        st.plotly_chart(fig2, use_container_width=True)

    _code("""
# Vendor market share — operating fleet
vendor_fleet = (
    reactors[reactors.status_group == "Operating"]
    .groupby("vendor")["capacity_mwe"]
    .sum().div(1000)
    .sort_values(ascending=False)
)
total_gwe = vendor_fleet.sum()
vendor_share = (vendor_fleet / total_gwe * 100).round(1)

print("Vendor share of operating fleet (%):")
print(vendor_share.head(10).to_string())

# Under construction — who is building now?
vendor_uc = (
    reactors[reactors.status_group == "Construction"]
    .groupby("vendor")["capacity_mwe"]
    .sum().div(1000)
    .sort_values(ascending=False)
)
print("\\nVendor share of UC pipeline (GWe):")
print(vendor_uc.head(8).round(1).to_string())
""")

    # ── 9. Construction duration ───────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 9. Construction Duration by Reactor Type")

    r_both = reactors[
        reactors.construction_start_date.notna() &
        reactors.commercial_operation_date.notna()
    ].copy()
    r_both["construction_start_date"]    = pd.to_datetime(r_both["construction_start_date"])
    r_both["commercial_operation_date"] = pd.to_datetime(r_both["commercial_operation_date"])
    r_both["build_years"] = (
        (r_both["commercial_operation_date"] - r_both["construction_start_date"])
        .dt.days / 365.25
    )
    r_both = r_both[(r_both["build_years"] > 1) & (r_both["build_years"] < 30)]

    if not r_both.empty:
        median_build = r_both["build_years"].median()
        fig = px.box(
            r_both, x="technology_family", y="build_years",
            color="technology_family", template="plotly_white",
            labels={"technology_family":"Technology","build_years":"Construction duration (years)"},
            points="all",
        )
        fig.add_hline(y=median_build, line_dash="dash", line_color="red",
                      annotation_text=f"Overall median: {median_build:.1f} yr")
        fig.update_layout(margin=dict(t=10), xaxis_title="",
                          showlegend=False, xaxis=dict(tickangle=-20))
        st.plotly_chart(fig, use_container_width=True)
        st.caption(
            f"Overall median construction duration: **{median_build:.1f} years**. "
            "Large first-of-a-kind units (EPR, AP1000) tend longer. "
            "Series-built designs (CPR-1000, VVER-1000) show tighter distributions."
        )

    _code("""
r_both = reactors[
    reactors.construction_start_date.notna() &
    reactors.commercial_operation_date.notna()
].copy()

r_both["construction_start_date"]    = pd.to_datetime(r_both["construction_start_date"])
r_both["commercial_operation_date"] = pd.to_datetime(r_both["commercial_operation_date"])

r_both["build_years"] = (
    (r_both["commercial_operation_date"] - r_both["construction_start_date"]).dt.days
    / 365.25
)

# Filter out obvious errors and outliers
r_valid = r_both[(r_both.build_years > 1) & (r_both.build_years < 30)]

by_type = r_valid.groupby("technology_family")["build_years"].agg(["median","mean","count"])
print("Construction duration (years) by technology:")
print(by_type.round(1).sort_values("median"))
""")

    # ── 10. Generation potential ───────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 10. Generation Potential at Different Capacity Factors")

    gwe_op = op["capacity_mwe"].sum() / 1000
    cf_range = [0.70, 0.75, 0.80, 0.85, 0.90, 0.93]
    gen_df = pd.DataFrame({
        "Capacity factor": [f"{int(cf*100)}%" for cf in cf_range],
        "TWh / year":      [round(gwe_op * cf * 8.76, 0) for cf in cf_range],
    })
    fig = px.bar(gen_df, x="Capacity factor", y="TWh / year",
                 template="plotly_white", color_discrete_sequence=["#10b981"],
                 text="TWh / year")
    fig.update_traces(textposition="outside")
    fig.update_layout(margin=dict(t=40), yaxis_title="TWh / year")
    st.plotly_chart(fig, use_container_width=True)
    st.caption(
        f"Operating fleet: **{gwe_op:,.1f} GWe**. "
        "At 85% CF (typical PWR), this is "
        f"**{gwe_op * 0.85 * 8.76:,.0f} TWh/year** — roughly 10% of global electricity."
    )

    _code("""
gwe_operating = reactors[reactors.status_group == "Operating"]["capacity_mwe"].sum() / 1000

print(f"Operating fleet: {gwe_operating:.1f} GWe")
print()
print(f"{'CF':>6}  {'TWh/yr':>10}")
print("-" * 20)
for cf in [0.70, 0.75, 0.80, 0.85, 0.90, 0.93]:
    twh = gwe_operating * cf * 8.76
    print(f"{cf*100:5.0f}%  {twh:>10,.0f}")
""")

    # ── 11. Maturity score distribution ──────────────────────────────────────
    st.markdown("---")
    st.markdown("### 11. Technology Maturity Score Distribution")

    tax_sorted = taxonomy.sort_values("maturity_score", ascending=False)
    fig = px.bar(
        tax_sorted, x="reactor_type", y="maturity_score",
        color="technology_family", template="plotly_white",
        labels={"reactor_type":"Reactor type","maturity_score":"Maturity score (0–100)",
                "technology_family":"Technology family"},
    )
    fig.add_hline(y=75, line_dash="dot", line_color="green",
                  annotation_text="Commercial (≥75)")
    fig.add_hline(y=55, line_dash="dot", line_color="orange",
                  annotation_text="Commercialising (≥55)")
    fig.update_layout(margin=dict(t=10), xaxis=dict(tickangle=-30))
    st.plotly_chart(fig, use_container_width=True)

    _code("""
taxonomy = pd.read_csv("data/processed/technology_taxonomy.csv")

# Maturity score formula:
# maturity_score = base_maturity
#                + known_operating_units  * 1.2
#                + known_under_construction_units * 1.8

print(taxonomy[["reactor_type","technology_family","maturity_score",
                "commercial_maturity_level","known_operating_units",
                "known_under_construction_units"]]
      .sort_values("maturity_score", ascending=False)
      .to_string(index=False))
""")

    _method(
        data="reactors_master.csv · reactor_pipeline.csv · country_nuclear_profile.csv · "
             "technology_taxonomy.csv — all generated by `run_pipeline.py`",
        features="capacity_mwe · status_group · technology_family · age_years · "
                 "commercial_operation_date · construction_start_date · vendor · region · "
                 "nuclear_share_percent · maturity_score",
        notes="All sections are descriptive — no predictive model. "
              "Each 'Show code' block contains the exact pandas/plotly code used.",
    )
